package io.github.YellowStoneTorch.SMP_Expansion.Equipment;

import io.github.YellowStoneTorch.SMP_Expansion.Equipment.Enchantments.EnchantmentType;
import org.bukkit.inventory.ItemStack;
import org.bukkit.persistence.PersistentDataType;
import org.jetbrains.annotations.Contract;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Unmodifiable;

import java.util.List;

import static io.github.YellowStoneTorch.SMP_Expansion.CustomData.equipmentType;
import static io.github.YellowStoneTorch.SMP_Expansion.Equipment.Enchantments.EnchantmentType.*;

/**
 * Defines equipment type for determining valid enchantments
 * @author YellowStoneTorch
 * @version 0.1.0_ALPHA
 */
public enum EquipmentType {
	SWORD(UNBREAKING, SHARPNESS, SMITE, BANE_OF_ARTHROPODS, FIRE_ASPECT, KNOCKBACK, LOOTING, SWEEPING_EDGE, MENDING, VANISHING_CURSE),
	GOLDEN_SWORD(UNBREAKING, SHARPNESS, SMITE, BANE_OF_ARTHROPODS, FIRE_ASPECT, KNOCKBACK, LOOTING, SWEEPING_EDGE, MENDING, VANISHING_CURSE),
	SPEAR(UNBREAKING, SHARPNESS, SMITE, BANE_OF_ARTHROPODS, FIRE_ASPECT, KNOCKBACK, LOOTING, LUNGE, MENDING, VANISHING_CURSE),
	GOLDEN_SPEAR(UNBREAKING, SHARPNESS, SMITE, BANE_OF_ARTHROPODS, FIRE_ASPECT, KNOCKBACK, LOOTING, LUNGE, MENDING, VANISHING_CURSE),
	AXE(UNBREAKING, SHARPNESS, SMITE, BANE_OF_ARTHROPODS, EFFICIENCY, FORTUNE, SILK_TOUCH, MENDING, VANISHING_CURSE),
	GOLDEN_AXE(UNBREAKING, SHARPNESS, SMITE, BANE_OF_ARTHROPODS, FIRE_ASPECT, KNOCKBACK, LOOTING, SWEEPING_EDGE, MENDING, VANISHING_CURSE),
	PICKAXE(UNBREAKING, EFFICIENCY, FORTUNE, SILK_TOUCH, MENDING, VANISHING_CURSE),
	GOLDEN_PICKAXE(UNBREAKING, EFFICIENCY, FORTUNE, SILK_TOUCH, MENDING, VANISHING_CURSE),
	SHOVEL(UNBREAKING, EFFICIENCY, FORTUNE, SILK_TOUCH, MENDING, VANISHING_CURSE),
	GOLDEN_SHOVEL(UNBREAKING, EFFICIENCY, FORTUNE, SILK_TOUCH, MENDING, VANISHING_CURSE),
	HOE(UNBREAKING, EFFICIENCY, FORTUNE, SILK_TOUCH, MENDING, VANISHING_CURSE),
	GOLDEN_HOE(UNBREAKING, EFFICIENCY, FORTUNE, SILK_TOUCH, MENDING, VANISHING_CURSE),
	HELMET(UNBREAKING, REINFORCEMENT, PROTECTION, BLAST_PROTECTION, FIRE_PROTECTION, AQUA_AFFINITY, RESPIRATION, THORNS, MENDING, BINDING_CURSE, VANISHING_CURSE),
	GOLDEN_HELMET(UNBREAKING, REINFORCEMENT, PROTECTION, BLAST_PROTECTION, FIRE_PROTECTION, AQUA_AFFINITY, RESPIRATION, THORNS, MENDING, BINDING_CURSE, VANISHING_CURSE),
	CHESTPLATE(UNBREAKING, REINFORCEMENT, PROTECTION, BLAST_PROTECTION, FIRE_PROTECTION, THORNS, MENDING, BINDING_CURSE, VANISHING_CURSE),
	GOLDEN_CHESTPLATE(UNBREAKING, REINFORCEMENT, PROTECTION, BLAST_PROTECTION, FIRE_PROTECTION, THORNS, MENDING, BINDING_CURSE, VANISHING_CURSE),
	LEGGINGS(UNBREAKING, REINFORCEMENT, PROTECTION, BLAST_PROTECTION, FIRE_PROTECTION, THORNS, MENDING, SWIFT_SNEAK, BINDING_CURSE, VANISHING_CURSE),
	GOLDEN_LEGGINGS(UNBREAKING, REINFORCEMENT, PROTECTION, BLAST_PROTECTION, FIRE_PROTECTION, THORNS, MENDING, SWIFT_SNEAK, BINDING_CURSE, VANISHING_CURSE),
	BOOTS(UNBREAKING, REINFORCEMENT, PROTECTION, BLAST_PROTECTION, FIRE_PROTECTION, DEPTH_STRIDER, FEATHER_FALLING, THORNS, MENDING, FROST_WALKER, SOUL_SPEED, BINDING_CURSE, VANISHING_CURSE),
	GOLDEN_BOOTS(UNBREAKING, REINFORCEMENT, PROTECTION, BLAST_PROTECTION, FIRE_PROTECTION, DEPTH_STRIDER, FEATHER_FALLING, THORNS, MENDING, FROST_WALKER, SOUL_SPEED, BINDING_CURSE, VANISHING_CURSE),
	BOW(UNBREAKING, POWER, FLAME, INFINITY, PUNCH, MENDING, VANISHING_CURSE),
	CROSSBOW(UNBREAKING, POWER, MULTISHOT, PIERCING, QUICK_CHARGE, MENDING, VANISHING_CURSE),
	TRIDENT(UNBREAKING, SHARPNESS, SMITE, BANE_OF_ARTHROPODS, IMPALING, CHANNELING, LOYALTY, RIPTIDE, MENDING, VANISHING_CURSE),
	MACE(UNBREAKING, SHARPNESS, SMITE, BANE_OF_ARTHROPODS, BREACH, DENSITY, MENDING, WIND_BURST, VANISHING_CURSE),
	FISHING_ROD(UNBREAKING, LUCK_OF_THE_SEA, LURE, MENDING, VANISHING_CURSE),
	SHEARS(UNBREAKING, EFFICIENCY, MENDING, VANISHING_CURSE),
	ELYTRA(UNBREAKING, MENDING, BINDING_CURSE, VANISHING_CURSE),
	WOLF_ARMOR(UNBREAKING, PROTECTION, THORNS, MENDING, BINDING_CURSE, VANISHING_CURSE),
	TOOL(UNBREAKING, MENDING, VANISHING_CURSE),
	WEARABLE(BINDING_CURSE, VANISHING_CURSE),
	VANISHABLE(VANISHING_CURSE),
	ENCHANTED_BOOK(EnchantmentType.values()),
	OTHER();

	private final EnchantmentType[] allowedEnchantments;

	EquipmentType(EnchantmentType... allowedEnchantments) {
		this.allowedEnchantments = allowedEnchantments;
	}

	/**
	 * Gets the type for the given name
	 * @param name name
	 * @return type
	 */
	public static EquipmentType getType(@NotNull String name) {
		try {
			return valueOf(name);
		}
		catch (IllegalArgumentException e) {
			return OTHER;
		}
	}

	/**
	 * Gets the type for the given item
	 * @param item item
	 * @return type
	 */
	public static EquipmentType getType(@NotNull ItemStack item) {
		return getType(item.getItemMeta()
				.getPersistentDataContainer()
				.getOrDefault(equipmentType, PersistentDataType.STRING, "OTHER"));
	}

	/**
	 * Returns a list of all allowed enchantments on this equipment type
	 * @return list of allowed enchantments
	 */
	@Contract(pure = true)
	@Unmodifiable
	public List<EnchantmentType> getAllowedEnchantments() {
		return List.of(allowedEnchantments);
	}
}
